// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: protolib/trie.proto

package trie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrieNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash   []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Prefix []byte `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Leaf and children are no longer mutually exclusive
	// Can have one or both, to support variable key length
	Children []*ChildEntry `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	IsLeaf   bool          `protobuf:"varint,4,opt,name=is_leaf,json=isLeaf,proto3" json:"is_leaf,omitempty"`
	LeafData []byte        `protobuf:"bytes,5,opt,name=leaf_data,json=leafData,proto3" json:"leaf_data,omitempty"`
}

func (x *TrieNode) Reset() {
	*x = TrieNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protolib_trie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrieNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrieNode) ProtoMessage() {}

func (x *TrieNode) ProtoReflect() protoreflect.Message {
	mi := &file_protolib_trie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrieNode.ProtoReflect.Descriptor instead.
func (*TrieNode) Descriptor() ([]byte, []int) {
	return file_protolib_trie_proto_rawDescGZIP(), []int{0}
}

func (x *TrieNode) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *TrieNode) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *TrieNode) GetChildren() []*ChildEntry {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *TrieNode) GetIsLeaf() bool {
	if x != nil {
		return x.IsLeaf
	}
	return false
}

func (x *TrieNode) GetLeafData() []byte {
	if x != nil {
		return x.LeafData
	}
	return nil
}

type ChildEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` //postfix
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *ChildEntry) Reset() {
	*x = ChildEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protolib_trie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChildEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildEntry) ProtoMessage() {}

func (x *ChildEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protolib_trie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildEntry.ProtoReflect.Descriptor instead.
func (*ChildEntry) Descriptor() ([]byte, []int) {
	return file_protolib_trie_proto_rawDescGZIP(), []int{1}
}

func (x *ChildEntry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ChildEntry) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

var File_protolib_trie_proto protoreflect.FileDescriptor

var file_protolib_trie_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6c, 0x69, 0x62, 0x2f, 0x74, 0x72, 0x69, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x6e, 0x6f, 0x77, 0x62, 0x6c, 0x6f, 0x73, 0x73,
	0x6f, 0x6d, 0x22, 0xa1, 0x01, 0x0a, 0x08, 0x54, 0x72, 0x69, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x33, 0x0a, 0x08, 0x63,
	0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x73, 0x6e, 0x6f, 0x77, 0x62, 0x6c, 0x6f, 0x73, 0x73, 0x6f, 0x6d, 0x2e, 0x43, 0x68, 0x69, 0x6c,
	0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6c, 0x65, 0x61, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x69, 0x73, 0x4c, 0x65, 0x61, 0x66, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x61,
	0x66, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6c, 0x65,
	0x61, 0x66, 0x44, 0x61, 0x74, 0x61, 0x22, 0x32, 0x0a, 0x0a, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x42, 0x4b, 0x0a, 0x16, 0x73, 0x6e,
	0x6f, 0x77, 0x62, 0x6c, 0x6f, 0x73, 0x73, 0x6f, 0x6d, 0x2e, 0x74, 0x72, 0x69, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x42, 0x09, 0x54, 0x72, 0x69, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x24, 0x67, 0x6f, 0x2e, 0x73, 0x6e, 0x6f, 0x77, 0x62, 0x6c, 0x6f, 0x73, 0x73, 0x6f,
	0x6d, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x62, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x74, 0x72, 0x69, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protolib_trie_proto_rawDescOnce sync.Once
	file_protolib_trie_proto_rawDescData = file_protolib_trie_proto_rawDesc
)

func file_protolib_trie_proto_rawDescGZIP() []byte {
	file_protolib_trie_proto_rawDescOnce.Do(func() {
		file_protolib_trie_proto_rawDescData = protoimpl.X.CompressGZIP(file_protolib_trie_proto_rawDescData)
	})
	return file_protolib_trie_proto_rawDescData
}

var file_protolib_trie_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protolib_trie_proto_goTypes = []interface{}{
	(*TrieNode)(nil),   // 0: snowblossom.TrieNode
	(*ChildEntry)(nil), // 1: snowblossom.ChildEntry
}
var file_protolib_trie_proto_depIdxs = []int32{
	1, // 0: snowblossom.TrieNode.children:type_name -> snowblossom.ChildEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protolib_trie_proto_init() }
func file_protolib_trie_proto_init() {
	if File_protolib_trie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protolib_trie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrieNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protolib_trie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChildEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protolib_trie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protolib_trie_proto_goTypes,
		DependencyIndexes: file_protolib_trie_proto_depIdxs,
		MessageInfos:      file_protolib_trie_proto_msgTypes,
	}.Build()
	File_protolib_trie_proto = out.File
	file_protolib_trie_proto_rawDesc = nil
	file_protolib_trie_proto_goTypes = nil
	file_protolib_trie_proto_depIdxs = nil
}
